# используем язык java. Travis CI поддерживает другие языки тоже.
env:
  global:
    - CODECOV_TOKEN="162524bb-e871-456f-8c61-8c3d9d45a29e"
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту geohound90@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - geohound90@gmail.com
    on_success: never # default: change
    on_failure: always # default: always